env:
  global:
    - DOCKER_REPO=partixyz/users-api
    - secure: f5aTt6SlBzDe591xHSWB68WVd2svpaFr+/2MNGCfrPg3fA44qh3hfggTlaRFeVm09PUHebm0bL9bgMiD53mrw8xXZKfnKRV5j34eyzg0gtu28/heyFiYQKB3py+TsW47MEwspoHFWLIu/d9esbGhj/omzcWf4zjI3MrneP9LlCand1p7KeVhl7zAfupttfqd4GinUV16UScXZu34L012rh/cxGXst9AaCZCKWn3o88O9mLXT9Hq4oViBxMB/99ewAsmkgrQWBC9TaIRmZUlL3nhPlYiAVloZ2U7mcFODpwTpCXCwC08KzAkgh3x1CKmp6PR9PQ4PSIZrIPFSdDxdHdsEhiy7zMfWzDXRkp8DRY2sjwgEQCB/D8V2tOaCRNa+72ztvVe13GlE/CU6lI43l0JeF/8crscBORDpb5tju04zIC7g5bp1Z3FueImDmrItw03pdz7g2BhpcTwLWawAlzoy07ckjBXx8XroeuAw7E6mplla4DGl+7doF4A/+9j1ytaVnhLEhsdLTlB8LRGCsLWRKPIWMdVXk5L7K1MKaCP9EdbIt+JSmgmGVqMdgm/2BgSsomQ7UqoDAMO4hV0vu0HklfIr1X2HmRd6/X1uocauXf9Jmif9H0VlRNXVXYlK5S0SfmN8y2htRmNivNYLQM/h3lvnG9CgeJavoS/qU2Y=
    - secure: HL4mmu/XCj3P2pGw8/XfpWRufq+PN+viUZV6MhIfmiZRlEftqF7d1BWyxPK4NFJBK9fvAsNPzal29urnymYqczFaaZF338vqHcCE8z853sKEUgGZ+u+QWSHgqXUyJp8KVhHmQ4ncRNUw7Vn5gsriYS3bjnG6kYzJNivhnJ16fwMgxscKwAnESGtXTt76qq/TtuuWTx5N0LopmM/aEi4FIIQlqX0s2imfNWEVxMwG3Cz7+AMuj33Tc4ryJEiLAyEVTnd0uCRayPCtJ57EhN95udOluG6Icf7/d3oAylH6dczuB8ORdVeG/tDqLWL5JsQYongtXoHCujJkRwxRS7rDuflyoijpFst+yubhKjwPGYwg9AKk+VX9HMB+JV14z1PIIC87lB/fH52g4ZZstnJGZm3XrhJ8QKKfrSyIDnBdeugPf98rUDfCF1FAO1AUQDrF6VcWtqmwQFBrj+/2MZlKtkfWyisXr//4Z7/Fsq+SVjYD9paUgBT46eGL1JTjkyRWNPKsZKWAVe24jUK0vBq1oJLJwlcF5AbvDet65hOTzM9vsK9HtV0jGfhhO4SGZLyheVFWrKm6yem49VtSOG8SzNPVVxj+fciWS2BWe3Y5L8DhpHxYAhT8fNbcPZav4uJNA9MpBNGUuyyWdmanq9ksKhTbtnmG7r3+spnucZfqFTA=
    - secure: Ge4wdL36IvXtTamlyXOiK0HMz3YVcd0nja75b1EWeWQEQ9iHw+ThIDCLxB945q6v7RO3bRRTzOeothykCVYnMRmzbDDkcbs1To9xZ3vbV6U+rFiFVbMUzGccRmh37dRuXWaFnMKwJstcnPo54fNNQiWQPfWFv4fcrPZkJ4iT61k26MR+do1Rp5mffiBiJPWKgQjG29xPyu8AsIIqbWiD0aN1+uz9P4IrIsr39jSgwuN2B0fm2minVCp92ebntOw/1x2YivSSSGmkSvzSVsJYpn3yGxK8KTbfdnOkNeYmG4TpBbnvXIMP5rCah0hmYKpicdS//yyL88Oa6otrKc/iU/hiBpZfdmJ0+30iQAw/cR21Nha815kS9H4wU9P7tfEUV/HQrclGDa+QaS6BKL0qY1ZeCoyU+rbheBO1jCGqpgfLEXr/WCl9+9xImhVQfh3/kaZw1Zihiy3wD+/VSFjobp+cYVCZ89UR4y0F4sYBvaFtW1SUWXZt137ODJWWiUaFaBd0Vsk6TrwMx+OZGrsqlFy8DIg4fERlqPwVlllm5ggFOzI1LV2UhpYsddtHecObBxy2J75JBRKXP6xDhO2CGkvT5QSUCnd8fwTlNjdUhWBbxyeDDrmzBmX5D4TVWlqJLmNSfSIt/1Hmb/rNI3cQDBT6lmgTncUh/6tna2lFHsQ=

language: ruby

rvm:
  - 2.3.0

sudo: true

addons:
  postgresql: 9.4

services:
  - docker

before_install:
  - gem install bundler

before_script:
  - export APP_VERSION=`git describe  --tags --long || echo ${TRAVIS_COMMIT::12}`
  - export DOCKER_IMAGE="$DOCKER_REPO:$APP_VERSION-travis"

script:
  - echo "building $DOCKER_IMAGE"
  - docker build -t $DOCKER_IMAGE .

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_REPO
