FROM ruby:2.3

RUN wget https://github.com/jwilder/dockerize/releases/download/v0.2.0/dockerize-linux-amd64-v0.2.0.tar.gz
RUN tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.2.0.tar.gz

RUN gem install bundler

RUN mkdir -p /parti/users-api 
WORKDIR /parti/users-api

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . ./

EXPOSE 3030
CMD ["deploy/docker-cmd.sh"]
