# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36d1176fb47f9b180bd9294f9332457ad4e6ba60e09ee0b5f374571ab299f425b1fc2dcf6c1374de9f247396454504be84f86b44caf5a8112166d096c8afc389

test:
  secret_key_base: e2a3d0d96e9694fa4f548b407268b55d8fb1e9d08fef9cd4edb3ac3fa9daa38edde7bd0be14e0b7440eb8401a2ce28c20218c6552f4ad1a5e664bec87e1f004d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
